/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_tmpsx5l24_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* nlp:(x,p[10])->(f,g[0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+10, w2, w3, w4, w5, w6, *w7=w+17;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = @0[:2] */
  for (rr=w1, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = 3 */
  w4 = 3.;
  /* #5: @4 = pow(@3,@4) */
  w4  = pow(w3,w4);
  /* #6: @2 = (@2*@4) */
  w2 *= w4;
  /* #7: @4 = @0[3] */
  for (rr=(&w4), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #8: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #9: @4 = (@4*@5) */
  w4 *= w5;
  /* #10: @2 = (@2+@4) */
  w2 += w4;
  /* #11: @4 = @0[4] */
  for (rr=(&w4), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #12: @4 = (@4*@3) */
  w4 *= w3;
  /* #13: @2 = (@2+@4) */
  w2 += w4;
  /* #14: @4 = @0[5] */
  for (rr=(&w4), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #15: @2 = (@2+@4) */
  w2 += w4;
  /* #16: @4 = @0[6] */
  for (rr=(&w4), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #17: @5 = 3 */
  w5 = 3.;
  /* #18: @5 = pow(@3,@5) */
  w5  = pow(w3,w5);
  /* #19: @4 = (@4*@5) */
  w4 *= w5;
  /* #20: @5 = @0[7] */
  for (rr=(&w5), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #21: @6 = sq(@3) */
  w6 = casadi_sq( w3 );
  /* #22: @5 = (@5*@6) */
  w5 *= w6;
  /* #23: @4 = (@4+@5) */
  w4 += w5;
  /* #24: @5 = @0[8] */
  for (rr=(&w5), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #25: @5 = (@5*@3) */
  w5 *= w3;
  /* #26: @4 = (@4+@5) */
  w4 += w5;
  /* #27: @5 = @0[9] */
  for (rr=(&w5), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #28: @4 = (@4+@5) */
  w4 += w5;
  /* #29: @7 = vertcat(@2, @4) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w4;
  /* #30: @1 = (@1-@7) */
  for (i=0, rr=w1, cs=w7; i<2; ++i) (*rr++) -= (*cs++);
  /* #31: @2 = ||@1||_F */
  w2 = sqrt(casadi_dot(2, w1, w1));
  /* #32: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}

/* nlp_f:(x,p[10])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+10, w2, w3, w4, w5, w6, *w7=w+17;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = @0[:2] */
  for (rr=w1, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = 3 */
  w4 = 3.;
  /* #5: @4 = pow(@3,@4) */
  w4  = pow(w3,w4);
  /* #6: @2 = (@2*@4) */
  w2 *= w4;
  /* #7: @4 = @0[3] */
  for (rr=(&w4), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #8: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #9: @4 = (@4*@5) */
  w4 *= w5;
  /* #10: @2 = (@2+@4) */
  w2 += w4;
  /* #11: @4 = @0[4] */
  for (rr=(&w4), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #12: @4 = (@4*@3) */
  w4 *= w3;
  /* #13: @2 = (@2+@4) */
  w2 += w4;
  /* #14: @4 = @0[5] */
  for (rr=(&w4), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #15: @2 = (@2+@4) */
  w2 += w4;
  /* #16: @4 = @0[6] */
  for (rr=(&w4), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #17: @5 = 3 */
  w5 = 3.;
  /* #18: @5 = pow(@3,@5) */
  w5  = pow(w3,w5);
  /* #19: @4 = (@4*@5) */
  w4 *= w5;
  /* #20: @5 = @0[7] */
  for (rr=(&w5), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #21: @6 = sq(@3) */
  w6 = casadi_sq( w3 );
  /* #22: @5 = (@5*@6) */
  w5 *= w6;
  /* #23: @4 = (@4+@5) */
  w4 += w5;
  /* #24: @5 = @0[8] */
  for (rr=(&w5), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #25: @5 = (@5*@3) */
  w5 *= w3;
  /* #26: @4 = (@4+@5) */
  w4 += w5;
  /* #27: @5 = @0[9] */
  for (rr=(&w5), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #28: @4 = (@4+@5) */
  w4 += w5;
  /* #29: @7 = vertcat(@2, @4) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w4;
  /* #30: @1 = (@1-@7) */
  for (i=0, rr=w1, cs=w7; i<2; ++i) (*rr++) -= (*cs++);
  /* #31: @2 = ||@1||_F */
  w2 = sqrt(casadi_dot(2, w1, w1));
  /* #32: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}

/* nlp_g:(x,p[10])->(g[0]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad:(x,p[10],lam_f,lam_g[0])->(f,g[0],grad_gamma_x,grad_gamma_p[10]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+28, w19, w20;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = @0[:2] */
  for (rr=w1, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = 3 */
  w4 = 3.;
  /* #5: @5 = pow(@3,@4) */
  w5  = pow(w3,w4);
  /* #6: @6 = (@2*@5) */
  w6  = (w2*w5);
  /* #7: @7 = @0[3] */
  for (rr=(&w7), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #8: @8 = sq(@3) */
  w8 = casadi_sq( w3 );
  /* #9: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #10: @6 = (@6+@9) */
  w6 += w9;
  /* #11: @9 = @0[4] */
  for (rr=(&w9), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #12: @10 = (@9*@3) */
  w10  = (w9*w3);
  /* #13: @6 = (@6+@10) */
  w6 += w10;
  /* #14: @10 = @0[5] */
  for (rr=(&w10), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #15: @6 = (@6+@10) */
  w6 += w10;
  /* #16: @10 = @0[6] */
  for (rr=(&w10), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #17: @11 = 3 */
  w11 = 3.;
  /* #18: @12 = pow(@3,@11) */
  w12  = pow(w3,w11);
  /* #19: @13 = (@10*@12) */
  w13  = (w10*w12);
  /* #20: @14 = @0[7] */
  for (rr=(&w14), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #21: @15 = sq(@3) */
  w15 = casadi_sq( w3 );
  /* #22: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #23: @13 = (@13+@16) */
  w13 += w16;
  /* #24: @16 = @0[8] */
  for (rr=(&w16), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #25: @17 = (@16*@3) */
  w17  = (w16*w3);
  /* #26: @13 = (@13+@17) */
  w13 += w17;
  /* #27: @17 = @0[9] */
  for (rr=(&w17), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #28: @13 = (@13+@17) */
  w13 += w17;
  /* #29: @18 = vertcat(@6, @13) */
  rr=w18;
  *rr++ = w6;
  *rr++ = w13;
  /* #30: @1 = (@1-@18) */
  for (i=0, rr=w1, cs=w18; i<2; ++i) (*rr++) -= (*cs++);
  /* #31: @6 = ||@1||_F */
  w6 = sqrt(casadi_dot(2, w1, w1));
  /* #32: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #33: @13 = input[2][0] */
  w13 = arg[2] ? arg[2][0] : 0;
  /* #34: @17 = (@13/@6) */
  w17  = (w13/w6);
  /* #35: @18 = (@17*@1) */
  for (i=0, rr=w18, cs=w1; i<2; ++i) (*rr++)  = (w17*(*cs++));
  /* #36: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<2; ++i) *rr++ = (- *cs++ );
  /* #37: {@17, @19} = vertsplit(@18) */
  w17 = w18[0];
  w19 = w18[1];
  /* #38: @16 = (@16*@19) */
  w16 *= w19;
  /* #39: @20 = (2.*@3) */
  w20 = (2.* w3 );
  /* #40: @14 = (@14*@19) */
  w14 *= w19;
  /* #41: @20 = (@20*@14) */
  w20 *= w14;
  /* #42: @16 = (@16+@20) */
  w16 += w20;
  /* #43: @20 = sq(@3) */
  w20 = casadi_sq( w3 );
  /* #44: @11 = (@11*@20) */
  w11 *= w20;
  /* #45: @10 = (@10*@19) */
  w10 *= w19;
  /* #46: @11 = (@11*@10) */
  w11 *= w10;
  /* #47: @16 = (@16+@11) */
  w16 += w11;
  /* #48: @9 = (@9*@17) */
  w9 *= w17;
  /* #49: @16 = (@16+@9) */
  w16 += w9;
  /* #50: @9 = (2.*@3) */
  w9 = (2.* w3 );
  /* #51: @7 = (@7*@17) */
  w7 *= w17;
  /* #52: @9 = (@9*@7) */
  w9 *= w7;
  /* #53: @16 = (@16+@9) */
  w16 += w9;
  /* #54: @9 = sq(@3) */
  w9 = casadi_sq( w3 );
  /* #55: @4 = (@4*@9) */
  w4 *= w9;
  /* #56: @2 = (@2*@17) */
  w2 *= w17;
  /* #57: @4 = (@4*@2) */
  w4 *= w2;
  /* #58: @16 = (@16+@4) */
  w16 += w4;
  /* #59: output[2][0] = @16 */
  if (res[2]) res[2][0] = w16;
  /* #60: @0 = zeros(10x1) */
  casadi_clear(w0, 10);
  /* #61: @13 = (@13/@6) */
  w13 /= w6;
  /* #62: @1 = (@13*@1) */
  for (i=0, rr=w1, cs=w1; i<2; ++i) (*rr++)  = (w13*(*cs++));
  /* #63: @18 = (-@1) */
  for (i=0, rr=w18, cs=w1; i<2; ++i) *rr++ = (- *cs++ );
  /* #64: {@13, @6} = vertsplit(@18) */
  w13 = w18[0];
  w6 = w18[1];
  /* #65: (@0[9] += @6) */
  for (rr=w0+9, ss=(&w6); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #66: @16 = (@3*@6) */
  w16  = (w3*w6);
  /* #67: (@0[8] += @16) */
  for (rr=w0+8, ss=(&w16); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #68: @15 = (@15*@6) */
  w15 *= w6;
  /* #69: (@0[7] += @15) */
  for (rr=w0+7, ss=(&w15); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #70: @12 = (@12*@6) */
  w12 *= w6;
  /* #71: (@0[6] += @12) */
  for (rr=w0+6, ss=(&w12); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #72: (@0[5] += @13) */
  for (rr=w0+5, ss=(&w13); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #73: @3 = (@3*@13) */
  w3 *= w13;
  /* #74: (@0[4] += @3) */
  for (rr=w0+4, ss=(&w3); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #75: @8 = (@8*@13) */
  w8 *= w13;
  /* #76: (@0[3] += @8) */
  for (rr=w0+3, ss=(&w8); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #77: @5 = (@5*@13) */
  w5 *= w13;
  /* #78: (@0[2] += @5) */
  for (rr=w0+2, ss=(&w5); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #79: (@0[:2] += @1) */
  for (rr=w0+0, ss=w1; rr!=w0+2; rr+=1) *rr += *ss++;
  /* #80: output[3][0] = @0 */
  casadi_copy(w0, 10, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    case 2: return "grad_gamma_x";
    case 3: return "grad_gamma_p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 32;
  return 0;
}

/* nlp_grad_f:(x,p[10])->(f,grad_f_x) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+10, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+24;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = @0[:2] */
  for (rr=w1, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = 3 */
  w4 = 3.;
  /* #5: @5 = pow(@3,@4) */
  w5  = pow(w3,w4);
  /* #6: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #7: @6 = @0[3] */
  for (rr=(&w6), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #8: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #9: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @7 = @0[4] */
  for (rr=(&w7), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #12: @8 = (@7*@3) */
  w8  = (w7*w3);
  /* #13: @5 = (@5+@8) */
  w5 += w8;
  /* #14: @8 = @0[5] */
  for (rr=(&w8), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #15: @5 = (@5+@8) */
  w5 += w8;
  /* #16: @8 = @0[6] */
  for (rr=(&w8), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #17: @9 = 3 */
  w9 = 3.;
  /* #18: @10 = pow(@3,@9) */
  w10  = pow(w3,w9);
  /* #19: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #20: @11 = @0[7] */
  for (rr=(&w11), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #21: @12 = sq(@3) */
  w12 = casadi_sq( w3 );
  /* #22: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #23: @10 = (@10+@12) */
  w10 += w12;
  /* #24: @12 = @0[8] */
  for (rr=(&w12), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #25: @13 = (@12*@3) */
  w13  = (w12*w3);
  /* #26: @10 = (@10+@13) */
  w10 += w13;
  /* #27: @13 = @0[9] */
  for (rr=(&w13), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #28: @10 = (@10+@13) */
  w10 += w13;
  /* #29: @14 = vertcat(@5, @10) */
  rr=w14;
  *rr++ = w5;
  *rr++ = w10;
  /* #30: @1 = (@1-@14) */
  for (i=0, rr=w1, cs=w14; i<2; ++i) (*rr++) -= (*cs++);
  /* #31: @5 = ||@1||_F */
  w5 = sqrt(casadi_dot(2, w1, w1));
  /* #32: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #33: @1 = (@1/@5) */
  for (i=0, rr=w1; i<2; ++i) (*rr++) /= w5;
  /* #34: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<2; ++i) *rr++ = (- *cs++ );
  /* #35: {@5, @10} = vertsplit(@1) */
  w5 = w1[0];
  w10 = w1[1];
  /* #36: @12 = (@12*@10) */
  w12 *= w10;
  /* #37: @13 = (2.*@3) */
  w13 = (2.* w3 );
  /* #38: @11 = (@11*@10) */
  w11 *= w10;
  /* #39: @13 = (@13*@11) */
  w13 *= w11;
  /* #40: @12 = (@12+@13) */
  w12 += w13;
  /* #41: @13 = sq(@3) */
  w13 = casadi_sq( w3 );
  /* #42: @9 = (@9*@13) */
  w9 *= w13;
  /* #43: @8 = (@8*@10) */
  w8 *= w10;
  /* #44: @9 = (@9*@8) */
  w9 *= w8;
  /* #45: @12 = (@12+@9) */
  w12 += w9;
  /* #46: @7 = (@7*@5) */
  w7 *= w5;
  /* #47: @12 = (@12+@7) */
  w12 += w7;
  /* #48: @7 = (2.*@3) */
  w7 = (2.* w3 );
  /* #49: @6 = (@6*@5) */
  w6 *= w5;
  /* #50: @7 = (@7*@6) */
  w7 *= w6;
  /* #51: @12 = (@12+@7) */
  w12 += w7;
  /* #52: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #53: @4 = (@4*@3) */
  w4 *= w3;
  /* #54: @2 = (@2*@5) */
  w2 *= w5;
  /* #55: @4 = (@4*@2) */
  w4 *= w2;
  /* #56: @12 = (@12+@4) */
  w12 += w4;
  /* #57: output[1][0] = @12 */
  if (res[1]) res[1][0] = w12;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "grad_f_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}

/* nlp_hess_l:(x,p[10],lam_f,lam_g[0])->(hess_gamma_x_x) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, w1, w2, *w3=w+12, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+25, w16, *w17=w+28, w18;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = @0[8] */
  for (rr=(&w1), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = @0[:2] */
  for (rr=w3, ss=w0+0; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #4: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #5: @5 = input[0][0] */
  w5 = arg[0] ? arg[0][0] : 0;
  /* #6: @6 = 3 */
  w6 = 3.;
  /* #7: @7 = pow(@5,@6) */
  w7  = pow(w5,w6);
  /* #8: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #9: @8 = @0[3] */
  for (rr=(&w8), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #10: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #11: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #12: @7 = (@7+@9) */
  w7 += w9;
  /* #13: @9 = @0[4] */
  for (rr=(&w9), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #14: @10 = (@9*@5) */
  w10  = (w9*w5);
  /* #15: @7 = (@7+@10) */
  w7 += w10;
  /* #16: @10 = @0[5] */
  for (rr=(&w10), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #17: @7 = (@7+@10) */
  w7 += w10;
  /* #18: @10 = @0[6] */
  for (rr=(&w10), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #19: @11 = 3 */
  w11 = 3.;
  /* #20: @12 = pow(@5,@11) */
  w12  = pow(w5,w11);
  /* #21: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #22: @13 = @0[7] */
  for (rr=(&w13), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #23: @14 = sq(@5) */
  w14 = casadi_sq( w5 );
  /* #24: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #25: @12 = (@12+@14) */
  w12 += w14;
  /* #26: @14 = (@1*@5) */
  w14  = (w1*w5);
  /* #27: @12 = (@12+@14) */
  w12 += w14;
  /* #28: @14 = @0[9] */
  for (rr=(&w14), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #29: @12 = (@12+@14) */
  w12 += w14;
  /* #30: @15 = vertcat(@7, @12) */
  rr=w15;
  *rr++ = w7;
  *rr++ = w12;
  /* #31: @3 = (@3-@15) */
  for (i=0, rr=w3, cs=w15; i<2; ++i) (*rr++) -= (*cs++);
  /* #32: @7 = ||@3||_F */
  w7 = sqrt(casadi_dot(2, w3, w3));
  /* #33: @2 = (@2/@7) */
  w2 /= w7;
  /* #34: @12 = sq(@5) */
  w12 = casadi_sq( w5 );
  /* #35: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #36: @12 = (@4*@12) */
  w12  = (w4*w12);
  /* #37: @14 = (2.*@5) */
  w14 = (2.* w5 );
  /* #38: @14 = (@8*@14) */
  w14  = (w8*w14);
  /* #39: @12 = (@12+@14) */
  w12 += w14;
  /* #40: @12 = (@12+@9) */
  w12 += w9;
  /* #41: @14 = sq(@5) */
  w14 = casadi_sq( w5 );
  /* #42: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #43: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #44: @16 = (2.*@5) */
  w16 = (2.* w5 );
  /* #45: @16 = (@13*@16) */
  w16  = (w13*w16);
  /* #46: @14 = (@14+@16) */
  w14 += w16;
  /* #47: @14 = (@14+@1) */
  w14 += w1;
  /* #48: @15 = vertcat(@12, @14) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w14;
  /* #49: @17 = (@2*@15) */
  for (i=0, rr=w17, cs=w15; i<2; ++i) (*rr++)  = (w2*(*cs++));
  /* #50: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) *rr++ = (- *cs++ );
  /* #51: @12 = (@2/@7) */
  w12  = (w2/w7);
  /* #52: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<2; ++i) *rr++ = (- *cs++ );
  /* #53: @14 = dot(@3, @15) */
  w14 = casadi_dot(2, w3, w15);
  /* #54: @14 = (@14/@7) */
  w14 /= w7;
  /* #55: @12 = (@12*@14) */
  w12 *= w14;
  /* #56: @15 = (@3*@12) */
  for (i=0, rr=w15, cr=w3; i<2; ++i) (*rr++)  = ((*cr++)*w12);
  /* #57: @17 = (@17-@15) */
  for (i=0, rr=w17, cs=w15; i<2; ++i) (*rr++) -= (*cs++);
  /* #58: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<2; ++i) *rr++ = (- *cs++ );
  /* #59: {@12, @14} = vertsplit(@17) */
  w12 = w17[0];
  w14 = w17[1];
  /* #60: @1 = (@1*@14) */
  w1 *= w14;
  /* #61: @3 = (@2*@3) */
  for (i=0, rr=w3, cs=w3; i<2; ++i) (*rr++)  = (w2*(*cs++));
  /* #62: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<2; ++i) *rr++ = (- *cs++ );
  /* #63: {@2, @7} = vertsplit(@3) */
  w2 = w3[0];
  w7 = w3[1];
  /* #64: @16 = (@13*@7) */
  w16  = (w13*w7);
  /* #65: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #66: @18 = (2.*@5) */
  w18 = (2.* w5 );
  /* #67: @13 = (@13*@14) */
  w13 *= w14;
  /* #68: @18 = (@18*@13) */
  w18 *= w13;
  /* #69: @16 = (@16+@18) */
  w16 += w18;
  /* #70: @1 = (@1+@16) */
  w1 += w16;
  /* #71: @7 = (@10*@7) */
  w7  = (w10*w7);
  /* #72: @16 = (2.*@5) */
  w16 = (2.* w5 );
  /* #73: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #74: @7 = (@7*@16) */
  w7 *= w16;
  /* #75: @16 = sq(@5) */
  w16 = casadi_sq( w5 );
  /* #76: @11 = (@11*@16) */
  w11 *= w16;
  /* #77: @10 = (@10*@14) */
  w10 *= w14;
  /* #78: @11 = (@11*@10) */
  w11 *= w10;
  /* #79: @7 = (@7+@11) */
  w7 += w11;
  /* #80: @1 = (@1+@7) */
  w1 += w7;
  /* #81: @9 = (@9*@12) */
  w9 *= w12;
  /* #82: @1 = (@1+@9) */
  w1 += w9;
  /* #83: @9 = (@8*@2) */
  w9  = (w8*w2);
  /* #84: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #85: @7 = (2.*@5) */
  w7 = (2.* w5 );
  /* #86: @8 = (@8*@12) */
  w8 *= w12;
  /* #87: @7 = (@7*@8) */
  w7 *= w8;
  /* #88: @9 = (@9+@7) */
  w9 += w7;
  /* #89: @1 = (@1+@9) */
  w1 += w9;
  /* #90: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #91: @9 = (2.*@5) */
  w9 = (2.* w5 );
  /* #92: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #93: @2 = (@2*@9) */
  w2 *= w9;
  /* #94: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #95: @6 = (@6*@5) */
  w6 *= w5;
  /* #96: @4 = (@4*@12) */
  w4 *= w12;
  /* #97: @6 = (@6*@4) */
  w6 *= w4;
  /* #98: @2 = (@2+@6) */
  w2 += w6;
  /* #99: @1 = (@1+@2) */
  w1 += w2;
  /* #100: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_hess_l_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i){
  switch (i) {
    case 0: return "hess_gamma_x_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}

/* nlp_jac_g:(x,p[10])->(g[0],jac_g_x[0]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_jac_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    case 1: return "jac_g_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
